plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android' version '2.1.10' // 2.1.0
}

group 'com.memtopia.trust_wallet_core'
version '1.0-SNAPSHOT'

repositories {
    google()
    mavenCentral()
}

android {
    namespace "com.memtopia.trust_wallet_core"
    compileSdk = 36

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = "1.8"
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
        main.jniLibs.srcDirs += 'src/main/jniLibs'
    }
    defaultConfig {
        minSdk = 23
    }
}